version: '3.4'

services:
  show-case-base-image:
    image: show-case-base-image
    build:
      context: ..
      dockerfile: ./docker-compose/Dockerfile
  test-case-coverage-detector:
    image: show-case-base-image
    depends_on: 
      - spring-boot-example
    container_name: show-case.test-case-coverage-detector
    environment: 
      aServiceJarLocation: /app/aService-0.0.1-SNAPSHOT.jar
    entrypoint: java -cp /app/out.jar poc.example.ShowcaseSpringBoot
    ports:
      - "8090:8090"      
  spring-boot-example:
    image: show-case-base-image
    container_name: show-case.spring-boot-example
    entrypoint: java "-javaagent:/app/jacocoagent.jar=address=*,port=20201,output=tcpserver,includes=com.example.*" -Djava.security.egd=file:/dev/./urandom -jar /app/aService-0.0.1-SNAPSHOT.jar
    ports: 
      - "8080:8080"