name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Install diff2html cli
      run:  sudo npm i -g diff2html-cli
    - name: Run tests
      run:  ./mill -i __.__.test
    - name: Generate coverage report
      run:  ./mill -i __.__.scoverage.xmlReport
    - name: Codecov
      uses: codecov/codecov-action@v1.0.11
      with:
        directory: ./out
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
